### ISSUE TITLE
IndexError : list index out of range

### ISSUE THREAD

**Issue by danydacosta** [aarreedd/CSV-to-ElasticSearch#11]
Hello,

I imported my [CSV file](https://files.danydc.ch/s/Y3mDsZij9zQBHY5) using this command :
```
python csv_to_elastic.py --elastic-address 'localhost:9200' --csv-file 'full_test.csv' --elastic-index 'stops_index' --datetime-field=dateField --json-struct '{"stop_id" : "%stop_id%", "stop_name" : "%stop_name%", "stop_lat" : "%stop_lat%", "stop_lon" : "%stop_lon%"}'
```

and I got this output :
```
 ----- CSV to ElasticSearch -----
Importing all rows into `stops_index` from 'full_test.csv'

Traceback (most recent call last):
  File "csv_to_elastic.py", line 130, in <module>
    elastic_address=parsed_args.elastic_address, id_column=parsed_args.id_column)
  File "csv_to_elastic.py", line 54, in main
    int(row[pos])
IndexError: list index out of range
Microsoft Windows [version 10.0.16299.371]
(c) 2017 Microsoft Corporation. Tous droits r▒serv▒s.
```

I'm running Python 3.6.5 on Windows 10.

Thank you in advance!

**Comment by aarreedd** [comment]
I don't see a column called stops_index on your CSV. I think that might be
the problem.

**Comment by danydacosta** [comment]
In the example you gave in the README, there is no column "index" in the CSV. The `--elastic-index` is made to specify the index in elasticsearch. Am I wrong?

**Comment by danydacosta** [comment]
Ok I tried several things and on multiple computers/OS and I noticed that the error was caused because my .csv file contains too many rows (30'000+). Have you tried using the .csv file I provided you? If so did you have the same issue? Thanks in advance.
