### ISSUE TITLE
First column in CSV is not imported.

### ISSUE THREAD

**Issue by Walter-Ullon** [aarreedd/CSV-to-ElasticSearch#14]
I'm having issues with the first column of the file not being imported into Elasticsearch. First discovered this issue when I tried to set the first column as the "id" and it couldn't be found. 

After importing my CSV, I tried a search by items in first column and it returned empty. 

Is this by design? Are we supposed to be inserting a blank column in position 1?

**Comment by th-alanreed** [comment]
You need a header column with the column names.
