### ISSUE TITLE
Returned status code: 401

### ISSUE THREAD

**Issue by April-Cai** [aarreedd/CSV-to-ElasticSearch#7]
I feel so lucky to find this amazing tool for quick importing csv file to elastic and thanks a lot!
While I am new to python and came into a problem: it ran properly but returned 401 in the console.
I would appreciate so much if you can check and tell me what's wrong.

1 console 
$ python3 csv_to_elastic.py  --json-struct '{"answer" : "%answer%","question" : "%question%"}' --csv-file data.csv --elastic-index qa    --elastic-address 'localhost:9200'

 ----- CSV to ElasticSearch ----- 
Importing all rows into `qa` from 'data.csv'

Reached end of CSV - sending to Elastic
Returned status code: 401

2 I put  data.csv in the same direction of py script and it looks like this:

answer | question
A1         |  Q1

3 my index name is qa

Thanks a lot :)

**Comment by aarreedd** [comment]
https://httpstatuses.com/401

---
*Alan Reed*
*Founder, Proud Development, LLC*

<https://www.prouddev.com>

**Comment by April-Cai** [comment]
Thank you for your reply!
I added authorization and it worked :) I suppose this is necessary for x-pack users.
